[project]
name = "latest-models-comparison"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.7.0",
    "matplotlib>=3.10.7",
    "notebook>=7.5.0",
    "playwright>=1.56.0",
    "scrapy>=2.13.4",
    "scrapy-playwright>=0.0.44",
]
